-- ============================================================
-- Distance Traveled — Seed: dt_days (default curriculum)
-- cohort_id = NULL means visible to all enrolled students.
-- Apply after dt-schema.sql.
-- ============================================================

INSERT INTO dt_days (id, cohort_id, week, region, date_label, title, type, coords_x, coords_y, location, key_skill, concepts, theory_name, theory_author, theory_summary, hook, note, earned_key, display_order)
VALUES

('pre-1', NULL, 0, 'The Compass Harbor', 'June 8 – 21', 'Forging the Compass Needle', 'foundation', 500, 220, NULL,
 'Self-Awareness & Values Alignment',
 '["Grit Scale (Duckworth)","Hidden Potential Character Quiz (Grant)","Primal Self-Assessment (Fletcher)","Two Core Values Audit (Brown)","Pre-Mortem Part I","Creature of Discomfort Commitment"]',
 'Growth Mindset', 'Carol Dweck',
 'Intelligence and ability are malleable. Struggle is biological evidence of new neural connections forming.',
 'Without an internal compass, every difficult moment this summer gets navigated by instinct alone. Your instincts will tell you to protect yourself. Your values compass will tell you to grow.',
 NULL, NULL, 0),

('w1-mon-am', NULL, 1, 'The Character Range', 'Mon June 22 — Morning', 'Character Mechanics & The Sponge Mindset', 'class', 320, 540, NULL,
 'Absorptive Capacity & Feedback Receptivity',
 '["Absorptive Capacity Spectrum: Rubber → Teflon → Clay → Sponge","Naturalness Bias","Effort Counts Twice (Duckworth)","Character vs. Instinct"]',
 'Authentic Leadership', 'Bill George',
 'Leaders defined by alignment between stated values and actual behavior under pressure. Build from the inside out.',
 'You are about to walk into a professional environment for the first time this summer. What version of yourself do you expect to show up? And what would it mean if the version that actually shows up is different from the one you expect?',
 NULL, NULL, 1),

('w1-mon-pm', NULL, 1, 'The Character Range', 'Mon June 22 — Evening', 'Identity Voting & The First Test', 'evening', 680, 640, NULL,
 'Followership & Inhibitory Control',
 '["Identity Voting (Clear) — every action is a vote","Inhibitory Control (the gap between stimulus and response)","Absorptive Capacity Matrix","Social Skydiving (Lewis)","Challenge Partner assignment"]',
 'Followership', 'Robert Kelley',
 'The most effective followers are active, independent, critical thinkers who commit fully. How you perform as a follower is the first measure of leadership potential.',
 'Tonight we test whether your values are real or just words. When you are exhausted and nobody is watching, which version of you shows up?',
 NULL, NULL, 2),

('w1-tue', NULL, 1, 'The Character Range', 'Tue June 23 — Morning', 'The Babble Effect & Mental Modes', 'class', 280, 770, NULL,
 'Scientist Mode vs. Loud Confidence',
 '["Babble Effect (groups follow loudness over competence)","Four Mental Modes: Scientist / Preacher / Prosecutor / Politician","Warren Harding Error","Standing Debate stress inoculation","Personal Preacher triggers"]',
 'Rethinking & Mental Modes', 'Adam Grant',
 'Scientist mode produces the best decisions under uncertainty: hold beliefs as hypotheses, revise when evidence changes.',
 'The last time a group you were in made a decision: was the person who made the call the most competent, or just the most confident? Why did everyone follow them anyway?',
 NULL, NULL, 3),

('w1-wed', NULL, 1, 'The Character Range', 'Wed June 24 — Morning', 'Intuition as Anomaly Detection', 'class', 720, 880, NULL,
 'The Intuition Pillar',
 '["Intuition as anomaly detection (not mysticism)","Effort × Effort = Achievement","Anomaly Detection Log","Proactivity as the behavioral expression of intuition"]',
 'Primal Intelligence: Intuition', 'Angus Fletcher',
 'Trained capacity to notice the small deviation that others rationalize away. Pattern recognition, not gut feeling.',
 'Something feels slightly off in your department. Do you flag it or file it away? That single habit separates exceptional leaders from competent ones.',
 NULL, NULL, 4),

('w1-thu', NULL, 1, 'The Character Range', 'Thu June 25 — Morning', 'Finite vs. Infinite Games', 'class', 360, 1010, NULL,
 'The Long Game',
 '["Finite vs. Infinite Games (Sinek/Carse)","Scientist Mode applied to Chamberlain","Junk the Plan Essay preview","Absorptive Capacity self-placement","The cause I am advancing is ___"]',
 'The Infinite Game', 'Simon Sinek',
 'Finite players optimize to win. Infinite players advance a cause that outlasts any single player. Leadership is not a finite game.',
 'Are you here to win the summer or to build something? Both are real answers. Only one of them will still matter in five years.',
 NULL, NULL, 5),

('w1-fri', NULL, 1, 'The Character Range', 'Fri June 26 — Field', 'Gettysburg & Little Round Top', 'field', 800, 1140, 'Gettysburg, PA',
 'Leadership Under Doctrine Failure',
 '["Lincoln Leadership Institute (morning)","Chamberlain bayonet charge case study","Moto vs. Logic on the battlefield","Junk the Plan Essay field notes"]',
 'Decision Under Doctrine Failure', 'Course Synthesis',
 'When every standard procedure has failed and the situation has outrun the plan, what does a leader do?',
 'Was Chamberlain''s bayonet charge crazy, or the most rational thing anyone could have done in that moment? You answer that on the ground he stood on.',
 NULL, NULL, 6),

('w1-internship', NULL, 1, 'The Character Range', 'Internship Week 1', 'Real Tests, Real Floor', 'internship', 160, 870, NULL,
 'Field Application',
 '["1.1 The Social Skydive — 3 high-stakes conversations","1.2 The Human Sponge Shadow — 1 hour of pure observation","1.3 Character vs. Instinct Daily Log — gap noticing M-F"]',
 'The Internship as Laboratory', 'Course Design',
 'Each concept introduced in class is assigned a real test in a real environment within the same week.',
 'The classroom is the operating manual. The internship is the operation.',
 NULL, NULL, 7),

('w2-mon-am', NULL, 2, 'The Forking River', 'Mon June 29 — Morning', 'When the Plan Breaks', 'class', 360, 1380, NULL,
 'Cognitive Agility & Narrative Intelligence',
 '["Story Thinking (Moto) vs. Logic","Branching Futures (Imagination Pillar)","Fresh Start Effect (Milkman)","System 1 / System 2 (Kahneman)","Confident Humility (Grant)"]',
 'Primal Intelligence: Imagination', 'Angus Fletcher',
 'Imagination = mapping what-if scenarios before the plan breaks. Logic deduces; Moto invents possibility when data is absent or contradictory.',
 'Your supervisor just changed the plan you spent three days preparing. In the next five minutes you have to come up with something new. What happens in your brain right now, and is what happens serving you?',
 NULL, NULL, 8),

('w2-mon-pm', NULL, 2, 'The Forking River', 'Mon June 29 — Evening', 'The Impossible Brief', 'evening', 720, 1490, NULL,
 'Designed Failure Under Pressure',
 '["The Impossible Brief (designed-failure exercise)","Neophilia vs. Nuance","Interest Development: trigger → practice → deepen","Bloom on talent development","Trident Plan introduction"]',
 'Designed Failure Pedagogy', 'Course Method',
 'Stress-inoculate the framework before you need it. The disruption forces a real-time switch from Logic to Moto under genuine pressure.',
 'In two weeks, you will be asked to admit a real mistake to a real supervisor in a real environment. What you feel tonight is what you will feel then. The difference is that now you will have practiced the response.',
 NULL, NULL, 9),

('w2-tue', NULL, 2, 'The Forking River', 'Tue June 30 — Morning', 'The Trident Plan & Wabi-Sabi Excellence', 'class', 280, 1620, NULL,
 'Branching Futures in Practice',
 '["Trident Plan: 1 Mountaintop Goal, 3 distinct tactical paths","Wabi-Sabi Excellence (strategic imperfectionism)","Near+1 Vigilance","Technology Audit (4 primal powers)"]',
 'Strategic Imperfectionism', 'Fletcher / Grant',
 'Choose what to let be imperfect so you can concentrate energy on what actually matters.',
 'Your phone gives you exactly what you want, when you want it. Your GPS reroutes around every obstacle. Now you are at an internship where none of that works. Can you invent a new path in real time? How would you know?',
 NULL, NULL, 10),

('w2-wed', NULL, 2, 'The Forking River', 'Wed July 1 — Morning', 'Proactive vs. Protective Learning', 'class', 740, 1750, NULL,
 'The Tutor Effect & Advice-Mode',
 '["Tutor Effect (teaching = deepest learning)","Proactive vs. Protective Learning","Advice vs. Feedback (the word change matters)","Prosocial Network Map","Technology Audit debrief"]',
 'The Loop of Progress', 'Adam Grant',
 'Show early imperfect work. Asking "what advice do you have?" activates coaching mode rather than critical mode.',
 'You have a deliverable. You know it isn''t as good as it could be. Submit and get feedback, or delay and protect yourself? What you choose tells you exactly where you are on the Absorptive Capacity spectrum.',
 NULL, NULL, 11),

('w2-thu', NULL, 2, 'The Forking River', 'Thu July 2 — Morning', 'The Unseen Narrative', 'class', 380, 1880, NULL,
 'Argument Structure Under Uncertainty',
 '["Junk the Plan Essay workshop","The Unseen Narrative","Deliberate practice (right kind only)","Defending Chamberlain rationally"]',
 'Beyond Probabilities', 'Course Synthesis',
 'Great leaders move beyond calculating probabilities to creating possibilities.',
 'What is the hardest argument to make in defense of Chamberlain''s decision? If you can write that version, you understand leadership under uncertainty.',
 NULL, NULL, 12),

('w2-internship', NULL, 2, 'The Forking River', 'Internship Week 2', 'Plan, Draft, Map', 'internship', 160, 1700, NULL,
 'Field Application',
 '["2.1 The Trident Plan — real project, 3 paths, supervisor input","2.2 The Rough Draft Challenge — early imperfect work","2.3 Prosocial Network Map — 3 unofficial influencers","Junk the Plan Essay (3-4 pages)"]',
 'Same-Week Application', 'Course Design',
 'You read about absorptive capacity Monday and demonstrate it at the internship by Wednesday.',
 'The challenges are not extra credit. They are the point.',
 NULL, NULL, 13),

('w3-mon-am', NULL, 3, 'The Compass Valley', 'Mon July 6 — Morning', 'Emotion as Diagnostic Signal', 'class', 380, 2200, NULL,
 'The Emotion Pillar',
 '["Fear = \"I have no plan\" → invent one immediate next step","Anger = \"I am trapped in only one plan\" → use Moto for 3 alternatives","Shame = \"split identity\" → return to values compass","Tuning Anxiety: Future Anxiety → Near+1 Vigilance","Emotion Signal Drill"]',
 'Emotional Intelligence', 'Daniel Goleman',
 'Self-Awareness, Self-Management, Social Awareness, Relationship Management. Fletcher''s Emotion Pillar operationalizes the first two with diagnostic precision.',
 'Something went wrong at your internship last week. Maybe you''re just flat. Those feelings are not random. They are precise diagnostic signals. Today we find out what each one means.',
 'This is the week most students find the hardest. The novelty is gone. The feedback has been honest, not encouraging. The gap between who you expected to be and who you are is uncomfortably visible. That is exactly where this week''s curriculum begins.',
 NULL, 14),

('w3-mon-pm', NULL, 3, 'The Compass Valley', 'Mon July 6 — Evening', 'Deliberate Practice & The Challenge Network', 'evening', 700, 2330, NULL,
 'Productive Disagreement',
 '["Deliberate practice (Ericsson) — targeted, feedback-intensive, on weakness","Task Conflict vs. Relationship Conflict (Edmondson)","Care Personally, Challenge Directly (Scott)","Building your Challenge Network"]',
 'Conflict Management Styles', 'Thomas-Kilmann',
 'Five modes: Competing / Collaborating / Compromising / Avoiding / Accommodating. Avoiding is almost always the most expensive choice over time.',
 'Elite performers specifically target their weakest areas. What is your equivalent of targeting weakness with deliberate practice — and are you actually doing it?',
 NULL, NULL, 15),

('w3-tue', NULL, 3, 'The Compass Valley', 'Tue July 7 — Morning', 'The Loop of Progress', 'class', 280, 2460, NULL,
 'Backing Up to Move Forward',
 '["The Loop of Progress (temporary decline before advance)","Three types of failure: basic / complex / intelligent","Beginner at the Next Level","Backing Up to Move Forward"]',
 'Intelligent Failure Typology', 'Amy Edmondson',
 'Only intelligent failure (small, hypothesis-driven errors in new territory) should be pursued deliberately.',
 'Your performance this week looks worse than two weeks ago — because you''re trying new things you''re not yet good at. Do you go back to what you were good at? Or stay in the discomfort and trust the research?',
 NULL, NULL, 16),

('w3-wed', NULL, 3, 'The Compass Valley', 'Wed July 8 — Morning', 'The Vulnerable Leader Equation', 'class', 740, 2590, NULL,
 'Trust Through Visible Imperfection',
 '["Vulnerable Leader Equation: Mistake + Demonstrated Competence = Psychological Safety","Armored vs. Daring leadership (Brown)","Feedback as investment, not evaluation (Wiseman)","Adversarial Peer Review","Naming your primary armor"]',
 'Daring Leadership', 'Brené Brown',
 'The daring leader removes their own armor before asking anyone else to remove theirs. Psychological safety cannot be mandated — only modeled.',
 'Your supervisor is watching how you handle the mistake — not the mistake itself. The admission of imperfection combined with demonstrated competence is a trust-building tool.',
 NULL, NULL, 17),

('w3-thu', NULL, 3, 'The Compass Valley', 'Thu July 9 — Morning', 'Antifragility & D.C. Preparation', 'class', 360, 2720, NULL,
 'Systems That Strengthen Under Stress',
 '["Antifragility design (stronger under stress, not just resistant)","Capitol: collective decision-making architecture","White House: Commander''s Intent in governance","Holocaust Museum: institutional failure of psychological safety"]',
 'Antifragility', 'Fletcher / Course Synthesis',
 'A system that uses stress as input for growth, rather than merely surviving it.',
 'The leadership question is not "how did this happen." It is: at what point did institutional structures fail to allow individuals to speak truth to power?',
 NULL, NULL, 18),

('w3-fri', NULL, 3, 'The Compass Valley', 'Fri July 10 — Field', 'D.C. — Three Sites, Three Frameworks', 'field', 820, 2850, 'Washington, D.C.',
 'Institutional Leadership at Scale',
 '["White House: scaling Commander''s Intent","U.S. Capitol: legislative process as Collective Intelligence architecture","Holocaust Museum: organizational conditions of dissent failure","D.C. Field Journal (3 sections, one per site)"]',
 'Psychological Safety at Catastrophic Scale', 'Edmondson Applied',
 'When silence is structurally easier than speech, what kind of organizational conditions made that true?',
 'Three sites in one day. The answer to "what does any of this have to do with leadership" is not inspiration — it is organizational leadership failure at a scale that killed millions.',
 NULL, NULL, 19),

('w3-internship', NULL, 3, 'The Compass Valley', 'Internship Week 3', 'Diagnose, Confess, Practice', 'internship', 140, 2530, NULL,
 'The Hardest Week''s Tests',
 '["3.1 Smart Signal Diagnostic Audit (Emotion Pillar applied to a real moment)","3.2 Vulnerability-Competence Briefing (proactively admit a mistake)","3.3 Deliberate Practice Design (target your single weakest skill)"]',
 'The Hardest Assignment', 'Course Design',
 'Admitting a real mistake to a real supervisor before they notice is the hardest professional skill in the program.',
 'It took real trust in your supervisor to do that. Acknowledging the honesty before addressing the mistake will make a lasting impression.',
 NULL, NULL, 20),

('w4-mon-am', NULL, 4, 'The Bridge of Crossing', 'Mon July 13 — Morning', 'Collective Intelligence', 'class', 380, 3060, NULL,
 'Prosocial Skills Beat Team IQ',
 '["Collective Intelligence (Grant)","Babble Effect at the group level","Brainwriting vs. Brainstorming","HIPPO effect (Highest Paid Person''s Opinion)","Chilean Mine Rescue case study","Three types of conversations (Duhigg)"]',
 'Maslow''s Hierarchy of Needs', 'Abraham Maslow',
 'You cannot lead others (belonging, esteem) until you have your own psychological foundation (safety, self-awareness) in place.',
 'In every group project: who did the work? Who came up with ideas? Who got credit? If those weren''t the same people, you''ve already experienced this week''s research finding — and it''s been costing your teams real performance for years.',
 NULL, NULL, 21),

('w4-mon-pm', NULL, 4, 'The Bridge of Crossing', 'Mon July 13 — Evening', 'Live with Dr. Angus Fletcher', 'evening', 720, 3170, NULL,
 'Direct Engagement With the Source',
 '["Live Zoom with Dr. Angus Fletcher","Pre-Mortem Part II partner debrief (unsealed from June)","Concept lived vs. concept still theoretical"]',
 'The Researcher in the Room', 'Course Method',
 'Bring concrete experiences from your life that you want to analyze through the primal intelligence lens — not abstract questions about his ideas.',
 'You have applied his frameworks at a Civil War battlefield, in your daily internship challenges, in your own emotional diagnostic work. The question you bring should not be about the book. It should be about your summer.',
 NULL, NULL, 22),

('w4-tue', NULL, 4, 'The Bridge of Crossing', 'Tue July 14 — Morning', 'Scaffolding & Fading', 'class', 280, 3300, NULL,
 'Teaching Without Creating Dependence',
 '["Scaffolding and Fading (Grant)","Tutor Effect at the leadership level","Legacy Scaffolding Blueprint","Lattice vs. Ladder","Autonomy + Mastery + Purpose (Pink)"]',
 'Situational Leadership', 'Hersey & Blanchard',
 'Adapt your style to the developmental level of the follower: Directing → Coaching → Supporting → Delegating.',
 'Your internship is almost over. What happens to four weeks of knowledge when you leave? Does it disappear, or can you structure it so it makes the next person better?',
 NULL, NULL, 23),

('w4-wed', NULL, 4, 'The Bridge of Crossing', 'Wed July 15 — Morning', 'Commander''s Intent', 'class', 740, 3430, NULL,
 'The Why and The Goal',
 '["Commander''s Intent: communicate the Why and Goal, empower the Middle","Job Crafting","Just Cause framework (Sinek)","Purpose as the most durable fuel for grit","Commander''s Intent role-play"]',
 'Servant Leadership', 'Robert Greenleaf',
 'The leader''s role is to serve the development of followers and the higher purpose. The leader goes last, not first.',
 'You''re writing a document for someone you''ve never met, for a role you''ve spent four weeks figuring out. Your job is to give the next person the freedom to think while making sure they understand why the work matters.',
 NULL, NULL, 24),

('w4-thu', NULL, 4, 'The Bridge of Crossing', 'Thu July 16 — Morning', 'The Lattice Pitch', 'class', 360, 3560, NULL,
 'Influence Without Title',
 '["Lattice vs. Ladder (informal influence networks)","The Lattice Pitch","Pre-Suasion (Cialdini): the moment before you speak"]',
 'Power Bases', 'French & Raven',
 'Five bases: Legitimate / Reward / Coercive / Expert / Referent. The most effective long-term leaders build Expert and Referent power.',
 'Tomorrow you sit with Dr. Angela Duckworth at Penn. The question is not "what did you think of your internship?" It is: where in your actual behavior do you see grit operating, and where do you see it failing?',
 NULL, NULL, 25),

('w4-fri', NULL, 4, 'The Bridge of Crossing', 'Fri July 17 — Field', 'Duckworth Roundtable at UPenn', 'field', 820, 3690, 'Wharton, Philadelphia, PA',
 'Conversation, Not Lecture',
 '["Academic roundtable with Dr. Angela Duckworth","Pre-submitted questions tied to internship evidence","Pre-course Grit Scale baseline as anchor"]',
 'Evidence-Based Self-Knowledge', 'Duckworth Applied',
 'You arrive with four weeks of internship evidence and engage her in conversation about what grit looks like under real professional conditions.',
 'The expectation is not that you come to listen. The expectation is that you arrive with evidence and engage.',
 NULL, NULL, 26),

('w4-internship', NULL, 4, 'The Bridge of Crossing', 'Internship Week 4 (Final)', 'Handbook, Brainwrite, Blueprint', 'internship', 140, 3360, NULL,
 'Final Field Application',
 '["4.1 Commander''s Intent Strategic Handbook (for your successor)","4.2 Brainwriting vs. Brainstorming Efficiency Report (joint with Challenge Partner)","4.3 Legacy Scaffolding Blueprint (visual fading schedule)"]',
 'Transformational vs. Transactional', 'Burns & Bass',
 'Transactional leaders manage. Transformational leaders elevate followers toward purpose beyond self-interest. Every Week 4 tool is transformational.',
 'If your supervisor has 10 minutes to tell you where you grew, where you plateaued, and what surprised them — that conversation will be one of the most valuable things in your entire summer.',
 NULL, NULL, 27),

('w5-mon', NULL, 5, 'The Synthesis Plateau', 'Mon July 20', 'Distance Traveled & Hope', 'class', 400, 3920, NULL,
 'Growth From Starting Position',
 '["Distance Traveled framework","Hope as a cognitive skill (not emotion)","Three dimensions of explanatory style: Permanence / Pervasiveness / Personalization","Brainwriting joint presentations","Internship debrief via Absorptive Capacity Matrix"]',
 'Learned Optimism', 'Martin Seligman',
 'Hope is a learned explanatory style that determines how you respond to setbacks and whether effort continues after failure.',
 'It''s been four weeks since you wrote your baseline philosophy. The distance between who you were June 8th and who you are July 20th is the only honest measure of what this summer produced in you.',
 NULL, NULL, 28),

('w5-tue', NULL, 5, 'The Synthesis Plateau', 'Tue July 21', 'Eating Your Enemy', 'class', 660, 4040, NULL,
 'Innovation Through Respect',
 '["\"Eating Your Enemy\" (Grant) — incorporate competitor strengths","Influential Listening","Looping for Understanding (Duhigg)","Range (Epstein)","10,000-hour framework (Gladwell vs. Ericsson)"]',
 'Range', 'David Epstein',
 'In complex, unpredictable domains, people with broad, varied experience consistently outperform narrow specialists.',
 'Genuine innovation comes from those who study what their strongest competitors do best and deliberately incorporate it. Can you do that with something from your own summer?',
 NULL, NULL, 29),

('w5-wed', NULL, 5, 'The Synthesis Plateau', 'Wed July 22', 'Self-Reliant Vision', 'class', 320, 4170, NULL,
 'The Common Sense Pillar',
 '["Common Sense Pillar (detection of unknown unknowns)","Self-Reliant Vision","Unleashing the Rookie","Technology Audit revisit"]',
 'Organizational Culture', 'Edgar Schein',
 'Three levels: Artifacts / Espoused Values / Underlying Assumptions. Leadership failures are born in the gap between Espoused Values and Underlying Assumptions.',
 'You are three weeks from your senior year. The scaffolding of high school is about to fall away. Do you trust your internal infrastructure enough to take the first step into uncertainty without waiting for permission?',
 NULL, NULL, 30),

('w5-thu', NULL, 5, 'The Synthesis Plateau', 'Thu July 23', 'Voice-Amplifying Systems', 'class', 700, 4300, NULL,
 'Structural Inclusion',
 '["Voice-Amplifying System design","Distance Traveled Portfolio assembly","Life Narrative organized around Valleys Crossed (not Peaks)","Final Synthesis Paper workshop"]',
 'Inclusive Leadership', 'Bourke & Dillon (Deloitte)',
 'Six traits: Commitment, Courage, Cognizance of Bias, Curiosity, Cultural Intelligence, Collaboration.',
 'Your final synthesis paper is the only assignment where the research evidence is your own summer. The question — what does it actually mean to lead? — can only be answered by someone who went somewhere, did something hard, failed at something real, and developed something durable.',
 NULL, NULL, 31),

('w5-fri', NULL, 5, 'The Synthesis Plateau', 'Fri July 24 — Field', 'U.S. Army War College', 'field', 820, 4430, 'Carlisle, PA',
 'Every Framework Activated Simultaneously',
 '["War Games Simulation","Think Tank Visit (20-year horizon)","Futures Lab","Senior Officers Roundtable"]',
 'The Capstone Test', 'Course Synthesis',
 'Every cognitive framework from the course activated simultaneously, on the highest-stakes ground available.',
 'Which course concept did you see validated most clearly here? Which one was revealed as more complex than the book suggested?',
 NULL, NULL, 32),

('w5-deliverables', NULL, 5, 'The Synthesis Plateau', 'Week 5 Deliverables', 'Putting It Together', 'internship', 140, 4140, NULL,
 'Synthesis Output',
 '["Collective Intelligence Comparative Case Study","Innovation Proposal","Voice-Amplifying System Proposal","Army War College Reflection"]',
 'The Bridge to Public Argument', 'Course Design',
 'Synthesis is not summary. It is the construction of a defensible argument from data collected across multiple environments.',
 'You are putting together a summer''s worth of development and building it into something you can articulate, defend, and use.',
 NULL, NULL, 33),

('w6-mon', NULL, 6, 'Distance Traveled Lookout', 'Mon July 27', 'The Identity Ballot Box', 'async', 380, 4670, NULL,
 'Counting the Votes',
 '["Atomic Habits Re-Read","How to Change Re-Read","Distance Traveled Portfolio assembly","Senior Year Commander''s Intent assigned","Re-read June 8th baseline"]',
 'Identity-Based Habits', 'James Clear',
 'You do not rise to the level of your goals; you fall to the level of your identity. Every action is a vote cast for the type of person you believe yourself to be.',
 'No class sessions this week. The scaffolding is removed. What remains is you, your work, your values compass, and a deadline.',
 NULL, NULL, 34),

('w6-tue', NULL, 6, 'Distance Traveled Lookout', 'Tue July 28', 'The Valleys Crossed', 'async', 700, 4790, NULL,
 'Honest Narrative',
 '["Just Cause re-read (Sinek)","Life Narrative Presentation: Valleys Crossed, not Peaks","Character Scorecard draft"]',
 'The Just Cause', 'Sinek (revisited)',
 'A goal has a finish line. A cause has a direction. Your presentation should not end with what you achieved — it should end with what you are now positioned to advance.',
 'The presentation is not a highlight reel. It is the honest account of this summer, organized around the moments that were hardest, most embarrassing, most disorienting, and most developmental.',
 NULL, NULL, 35),

('w6-wed', NULL, 6, 'Distance Traveled Lookout', 'Wed July 29', 'The Rule Rewrite', 'async', 320, 4910, NULL,
 'Change Leadership Applied',
 '["Rule Rewrite proposal","Schein''s Underlying Assumptions level","Goal vs. Cause distinction","Real institution, real problem, real proposed solution"]',
 'Change Leadership (8-Step)', 'John Kotter',
 'Create Urgency → Build Coalition → Form Vision → Communicate → Remove Obstacles → Short-Term Wins → Build on Change → Anchor in Culture.',
 'The Rule Rewrite asks you to identify a real rule that produces the opposite of its intended effect. Does it empower people inside the institution, or constrain them differently?',
 NULL, NULL, 36),

('w6-thu', NULL, 6, 'Distance Traveled Lookout', 'Thu July 30', 'The Personal Scaffolding Map', 'async', 700, 5040, NULL,
 'Naming Your Network',
 '["Personal Scaffolding Map (mentors, challenge network, connectors)","Senior Year Commander''s Intent finalization","Brown re-read (the armor question)","Final compilation","Naming who tells you what you don''t want to hear"]',
 'Faded Scaffolding', 'Course Synthesis',
 'Your map should include not just who supports you, but when that support should be faded.',
 'Senior year begins in four weeks. The scaffolding ends tomorrow. You need those answers before you leave for college, not after you arrive.',
 NULL, NULL, 37),

('w6-fri', NULL, 6, 'Distance Traveled Lookout', 'Fri July 31 — Deadline', 'The Last Test', 'deadline', 500, 5170, NULL,
 'Self-Directed Capacity',
 '["All deliverables submitted by 11:59 PM","Final Synthesis Paper (8-10 pp)","Life Narrative Presentation","Distance Traveled Portfolio","Character Scorecard","Rule Rewrite","Personal Scaffolding Map","Senior Year Commander''s Intent","SFD Journal compilation"]',
 'The Deadline as Diagnostic', 'Course Design',
 'What you do today, on a Friday in late July when no one is watching, tells you more about who you actually are than any field experience.',
 'The work is either done or it isn''t. The development is either real or it''s performed. You know which one it is.',
 NULL, NULL, 38),

('horizon', NULL, 7, 'The Horizon', 'Aug 8 → Sept 15 → Senior Year', 'What Continues After', 'horizon', 500, 5430, NULL,
 'Durable Identity',
 '["Aug 8 — Identity Re-Activation Text","Aug 15 — Cohort Re-Gathering (in-person, 2.5 hrs)","Weekly Challenge Partner texts (every Monday by 9 PM)","Sept 15 — Distance Traveled +30 Entry","Optional Fall check-ins"]',
 'Senior Year Bridge Protocol', 'Course Design',
 'What you built this summer will collapse without commitment devices that survive into senior year. Your principles don''t hold themselves; the structure holds them.',
 'This protocol exists to make sure the person you became this summer is still the person who shows up in September, October, and February — not a memory of someone who was briefly different.',
 NULL, NULL, 39)

ON CONFLICT DO NOTHING;
