// Terms of Service — pages/terms.js

import Head from "next/head";
import { Logo } from "../src/components/UI";

export default function TermsPage() {
  return (
    <>
      <Head>
        <title>Terms — imPROVED</title>
      </Head>
      <main style={{ minHeight: "100vh", maxWidth: 720, margin: "0 auto", padding: "40px 24px 80px" }}>
        <div style={{ marginBottom: 36 }}>
          <a href="/" style={{ textDecoration: "none" }}>
            <Logo size={22} />
          </a>
        </div>

        <h1
          style={{
            fontFamily: "var(--font-display)",
            fontSize: 36,
            fontWeight: 800,
            color: "var(--text-1)",
            marginBottom: 12,
          }}
        >
          Terms of Service
        </h1>
        <p style={{ fontSize: 13, color: "var(--text-4)", marginBottom: 36 }}>
          Last updated: May 2026
        </p>

        <Section heading="What this is">
          <P>
            imPROVED is a learning platform that helps people develop ten foundational skills
            through research-backed curriculum, real-world application, and a structured Defense
            submission with AI evaluation. Verifications generated by the platform document what
            a user actually completed. They are not academic credits or professional
            certifications; they are evidence of completed work.
          </P>
        </Section>

        <Section heading="Who can use it">
          <P>
            Accounts are purchased by adults age 18 or older, typically a parent or guardian, on
            behalf of a student of any age. By purchasing, the adult attests that they have legal
            authority over the account holder. The student is the user; the platform is designed
            for them.
          </P>
        </Section>

        <Section heading="What you're paying for">
          <P>
            <Strong>Free tier:</Strong> Skills 1 and 2 (Self-Awareness and Extreme Ownership), in
            full. No payment required.
          </P>
          <P>
            <Strong>Full Access ($39, one-time):</Strong> Permanent access to all 10 skills,
            permanent shareable Verification URLs, downloadable PDF credentials, and spaced
            revisit emails at 30, 90, and 180 days. No subscription, no recurring charges, no
            expiration on already-completed Verifications.
          </P>
          <P>
            <Strong>Verification Plus (+$19):</Strong> Designed PDF credentials, LinkedIn badge
            integration, and journaled record of all challenge documentation.
          </P>
          <P>
            <Strong>30-day money-back guarantee:</Strong> Reply to your receipt within 30 days
            for a full refund. No questions, no friction. Refunds delete your account and all
            data.
          </P>
        </Section>

        <Section heading="What we don't do">
          <Bullet>We don't make claims about employment outcomes. Verifications document completed work; whether they help with a specific job or college application is up to the reader.</Bullet>
          <Bullet>We don't replace professional services. The Defense evaluator is not a therapist, counselor, or medical provider. It judges written submissions; it does not coach, advise, or psychoanalyze. If you're in crisis, our overlay surfaces real resources — please use them.</Bullet>
          <Bullet>We don't guarantee skill mastery. Completing a skill on imPROVED means you did the documented work. Whether the skill becomes part of your life is determined by what you do after.</Bullet>
        </Section>

        <Section heading="Acceptable use">
          <P>
            Don't try to break the platform, don't impersonate other users, don't share your
            account credentials, and don't attempt to extract Verifications you didn't earn. We
            reserve the right to revoke access for misuse, with refund where appropriate.
          </P>
        </Section>

        <Section heading="If something goes wrong">
          <P>
            We provide imPROVED "as is." We work hard to keep it running and accurate, but
            services have outages. To the maximum extent permitted by law, we are not liable for
            indirect, incidental, or consequential damages. Our total liability for any claim is
            limited to what you paid.
          </P>
        </Section>

        <Section heading="Changes to these terms">
          <P>
            If we materially change these terms, we'll notify active users by email at least 30
            days before changes take effect. Continued use after that date means you accept the
            new terms.
          </P>
        </Section>

        <Section heading="Contact">
          <P>Questions: hello@improvedskills.com</P>
        </Section>
      </main>
    </>
  );
}

function Section({ heading, children }) {
  return (
    <section style={{ marginBottom: 40 }}>
      <h2
        style={{
          fontFamily: "var(--font-display)",
          fontSize: 18,
          fontWeight: 700,
          color: "var(--gold)",
          marginBottom: 14,
        }}
      >
        {heading}
      </h2>
      {children}
    </section>
  );
}

function P({ children }) {
  return (
    <p style={{ fontSize: 15, lineHeight: 1.95, color: "var(--text-2)", marginBottom: 16 }}>
      {children}
    </p>
  );
}

function Bullet({ children }) {
  return (
    <p
      style={{
        fontSize: 15,
        lineHeight: 1.95,
        color: "var(--text-2)",
        marginBottom: 12,
        paddingLeft: 18,
        position: "relative",
      }}
    >
      <span style={{ position: "absolute", left: 0, top: 8, width: 5, height: 5, borderRadius: "50%", background: "var(--gold)" }} />
      {children}
    </p>
  );
}

function Strong({ children }) {
  return <strong style={{ color: "var(--text-1)", fontWeight: 600 }}>{children}</strong>;
}
